baseURL = "https://daehyuny00.github.io/"
title = "Daehyun Tech Blog"
theme = "hugo-book"
defaultContentLanguage = "ko"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true
timeZone = "Asia/Seoul"
summaryLength = 180
disablePathToLower = true

[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

[permalinks]
posts = "/posts/:slugorcontentbasename/"

[outputs]
home = ["HTML", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = false
noClasses = false

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[languages]
[languages.ko]
languageName = "한국어"
languageCode = "ko-KR"
weight = 1
title = "Daehyun Tech Blog"
[languages.en]
languageName = "English"
languageCode = "en-US"
weight = 2
title = "Daehyun Tech Blog"
