[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Posts"
pageRef = "/posts"
weight = 2

[[main]]
name = "Papers"
pageRef = "/papers"
weight = 3

[[main]]
name = "Technology"
pageRef = "/technology"
weight = 4

[[main]]
name = "Tech Blogs"
pageRef = "/techblogs"
weight = 5

[[main]]
name = "About"
pageRef = "/about"
weight = 6
