[[main]]
name = "Papers"
pageRef = "/papers"
weight = 1

[[main]]
name = "Tech Blogs"
pageRef = "/techblogs"
weight = 2

[[main]]
name = "Insights"
pageRef = "/posts"
weight = 3

[[main]]
name = "Archive"
pageRef = "/archives"
weight = 4

[[main]]
name = "About"
pageRef = "/about"
weight = 5
