name = "lab-light"
license = "MIT"
licenselink = "https://opensource.org/license/mit/"
description = "Lightweight Hugo theme for technical writing"
homepage = "https://github.com/DaehyunY00/DaehyunY00.github.io"
min_version = "0.125.0"

[author]
name = "Daehyun Yoo"
homepage = "https://github.com/DaehyunY00"
